services:
  codespaces-ceidg:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        JDK_VERSION: 21
    volumes:
      - ../../:/workspace
    environment:
      SWAGGER_SERVER_PUBLIC_URL: http://localhost:8080
      SERVER_PORT: 8080
      JWT: ${USER_CODESPACE_CEIDG_JWT}
    command: sleep infinity
